### ISSUE TITLE
All graphs N/A kubernetes on google container engine

### ISSUE THREAD

**Issue by amitgilad3** [instrumentisto/grafana-dashboard-kubernetes-prometheus#4]
Hi ,

i deployed  prometheus  with scrape config you specified and and connected grafana to it and all my dashboards are N/A 

note : i am running with kubernetes v 1.7

any help would be appreciated

**Comment by tyranron** [comment]
@amitgilad3 this dashboard is meant for CoreOS Kubernetes installation mainly. Having `N/A` means that there are no metrics in Prometheus required by dashboard. The reason probably is that GCE kubelet do not expose them. You may check this by logging into Prometheus (via its web interface) and look up there what you have.

**Comment by jiminHuang** [comment]
Accounter with this issue when creating clusters via kubeadm. I deployed Prometheus and grafana via helm charts and finally fix this issue.

- Check out the status ``kubernetes-nodes-cadvisor`` of ``targets`` in the web UI of Prometheus.
- Add ``insecure_skip_verify: true`` in ``tls_config`` if it shows 503 or x509
- Or it shows ``server returned HTTP status 404 Not Found``
    - In Kubernetes 1.7.0-1.7.2, metrics are only exposed on the cAdvisor HTTP endpoint; use ``replacement: /api/v1/nodes/${1}:4194/proxy/metrics``, according to the [example](https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L50-L78)
    - kubeadm disables cAdvisor from listening to 0.0.0.0:4194 by default, so remove ``Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=0"`` in ``/etc/systemd/system/kubelet.service.d/10-kubeadm.conf``
- Additionally, I add following configurations in the scrape config. Since I'm new to prometheus, maybe they are not nessesary, but in this work around I manage to show all metrics in grafana.
```yaml
- target_label: __address__
    replacement: kubernetes.default.svc:443
- source_labels: [__meta_kubernetes_node_name]
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/nodes/${1}:4194/proxy/metrics
```
